---
title: "R Notebook"
output: html_notebook
---

```{r,echo=FALSE,warning=FALSE,message=FALSE}
# Load libraries
library(rgdal)
library(leaflet)
library(tidyverse)
library(rgeos)
library(raster)
library(ggplot2)
library(sf)
library(mapview)
library(maptools)
library(sp)
library(readxl)
library(readr)
library(grid)
library(gridExtra)
library(xtable)
library(knitr)
library(kableExtra)
library(plyr)
library(RColorBrewer)

source('../functions/localSnapPointsToLines.R')
source('../functions/nearest_line.R')
source('../functions/leaflet_map.R')
source('../functions/time_plot.R')
source('../functions/table_annual.R')
source('../functions/table_police.R')
source('../functions/buffer_data.R')
source('../functions/read_road_data.R')
source('../functions/filter_data.R')
source('../functions/delete_na.R')
source('../functions/count.R')
source('../functions/count_pre.R')
source('../functions/count_post.R')
source('../functions/count_impl.R')

##1.Data path 
dir_path <- "../data"
```

> Edinburgh's road network

```{r,echo=FALSE,warning=FALSE,message=FALSE} 
#Read geodatabase for Edinburgh
#Path
gdb_path <- paste0(dir_path, "/20mph.gdb")
gdb_layers <- ogrListLayers(gdb_path)

#Read shapefile
edin_cons_streets <- readOGR(dsn = gdb_path,layer="Consultation20mphStreets", verbose = FALSE)
#Put ID column as variable 
edin_cons_streets@data <-rowid_to_column(edin_cons_streets@data, "ID")
#Transform to long/lat
edin_cons_streets <- spTransform(edin_cons_streets, "+init=epsg:4326")

edin_road_network <- edin_cons_streets
edin_road_network <- edin_road_network[edin_road_network@data$LAYER  %in% c("20mph existing streets", "20mph local streets","20mph main streets","30mph","Part time 20mph"),]
edin_road_network <- spTransform(edin_road_network,"+init=epsg:4326")

```

> Edinburgh's implementation zones

```{r,echo=FALSE,warning=FALSE,message=FALSE}
#Read shapefile
edin_impl_zones <- readOGR(dsn = gdb_path, layer="ImplementationZones", verbose = FALSE)
#Transform to long/lat
edin_impl_zones <- spTransform(edin_impl_zones, "+init=epsg:4326")
#Change zone 1
edin_impl_zones@data$ImplementationZone <- as.integer(edin_impl_zones@data$ImplementationZone)
edin_impl_zones@data[6,]$ImplementationZone <- 7
#Visualize with leaflet

```

> Edinburgh's control zones

```{r,echo=FALSE,warning=FALSE,message=FALSE}
#Read control zones codes
control_1 <- read.delim(paste0(dir_path, "/control_zone_codes/controlzone1.txt"),stringsAsFactor = FALSE,header = FALSE)
control_3 <- read.delim(paste0(dir_path, "/control_zone_codes/controlzone3.txt"),stringsAsFactor = FALSE,header = FALSE)
control_3 <- c(control_3[,1],control_3[,2],control_3[,3],control_3[,4],control_3[,5],control_3[,6],control_3[,7],control_3[,8],control_3[,9])
control_4 <- read.delim(paste0(dir_path, "/control_zone_codes/controlzone4.txt"),stringsAsFactor = FALSE,header = FALSE)
control_5 <- read.delim(paste0(dir_path, "/control_zone_codes/controlzone5.txt"),stringsAsFactor = FALSE,header = FALSE)
control_6 <- read.delim(paste0(dir_path, "/control_zone_codes/controlzone6.txt"),stringsAsFactor = FALSE,header = FALSE)
control_7 <- read.delim(paste0(dir_path, "/control_zone_codes/controlzone7.txt"),stringsAsFactor = FALSE,header = FALSE)
control_all <- c(control_1,control_3,control_4,control_5,control_6,control_7)

#Path for control zones
control_gdb_path <- paste0(dir_path, "/SG_DataZoneBdry_2011")
control_gdb_layers <- ogrListLayers(control_gdb_path)

#Read data
edin_control_zone <- readOGR(dsn = control_gdb_path,layer="SG_DataZone_Bdry_2011", verbose = FALSE)
edin_control_zone <- spTransform(edin_control_zone, "+init=epsg:4326")
control_zone_all <- edin_control_zone[edin_control_zone@data$DataZone %in%  control_all,]

```


```{r,echo=FALSE,warning=FALSE,message=FALSE} 
#Read data
edin_road_data <- read_road_data()
control_zone_data <- read_csv(paste0(dir_path, "/edin_control_data.csv"))
control_zone_data <- control_zone_data %>% filter(control_zone_data$Speed_limit %in% c(20,30)) 
casualties_data <- read_csv(paste0(dir_path, "/edin_casualties_data.csv"))

#keep a copy for implementation zones
data <- edin_road_data
df <- data 
```

```{r, echo=FALSE, warning=FALSE,message=FALSE}
#Get nearest line for pre and post 20mph using the nearest_line function, use only layers we care edin_road network instead of edin_cons_streets
#nearest_road <- nearest_line(edin_road_data,edin_cons_streets)
#nearest_road <- spTransform(nearest_road,"+init=epsg:4326")
nearest_road <- nearest_line(edin_road_data,edin_road_network)
nearest_road <- spTransform(nearest_road,"+init=epsg:4326")
```

```{r, echo=FALSE, warning=FALSE,message=FALSE}
#Merge the dataframes based on the ID of the nearest line in order to connect geoinformation with stasts19
#Then merge Casualty severity column with collisions dataset
mergedDf <- unique(merge(data.frame(nearest_road),edin_road_network@data,by.x = "nearest_line_id" ,by.y = "ID"))
mergedDf <- rename(mergedDf,c("Longitude.x" = "Longitude","Latitude.x"="Latitude","year.x"="year","Speed_limit.x"="Speed_limit","Date.x"="Date"))
mergedDf$Date <- as.character(mergedDf$Date)

```

> Mapping accidents with roads: 2013/2014

```{r, echo=FALSE, warning=FALSE,message=FALSE}
p13 <- count_pre(mergedDf[mergedDf$Date >= "2013-07-31" & mergedDf$Date <= "2014-07-30" ,])
pre13 <- count_post(mergedDf[mergedDf$Date >= "2013-07-31" & mergedDf$Date <= "2014-07-30" ,])
```

> Mapping accidents with roads: 2014/2015

```{r, echo=FALSE, warning=FALSE,message=FALSE}
p14 <- count_pre(mergedDf[mergedDf$Date >= "2014-07-31" & mergedDf$Date <= "2015-07-30" ,]) 
pre14 <- count_post(mergedDf[mergedDf$Date >= "2014-07-31" & mergedDf$Date <= "2015-07-30" ,])
```

> Mapping accidents with roads: 2015/2016

```{r, echo=FALSE, warning=FALSE,message=FALSE}
p15 <- count_pre(mergedDf[mergedDf$Date >= "2015-07-31" & mergedDf$Date <= "2016-07-30" ,])
pre15 <- count_post(mergedDf[mergedDf$Date >= "2015-07-31" & mergedDf$Date <= "2016-07-30" ,])
```

> Count pre 20mph 

```{r,echo=FALSE,warning=FALSE,message=FALSE}
pre <- count_pre(mergedDf[mergedDf$Date >= "2013-07-31" & mergedDf$Date <= "2016-07-30" ,])
p <- count_post(mergedDf[mergedDf$Date >= "2013-07-31" & mergedDf$Date <= "2016-07-30" ,])
pre
p
```

> Count post 20mph

```{r,echo=FALSE,warning=FALSE,message=FALSE}
post <- count_pre(mergedDf[mergedDf$Date >= "2018-03-06" & mergedDf$Date <= "2019-06-31" ,])
po <- count_post(mergedDf[mergedDf$Date >= "2018-03-06" & mergedDf$Date <= "2019-06-31" ,])
post
po
```

> Table: Average annual road traffic collision rates in the city of Edinburgh 

```{r, echo=FALSE, warning=FALSE, message=FALSE}
table_annual(pre,post)
```

> Effect estimate

```{r,echo=FALSE,warning=FALSE,message=FALSE}
Tax_year <- c("Annual number of collisions","Rate per year"," ","% reduction in collisions ")
a <- sum(pre13[,2])
b <- sum(pre14[,2])
c <- sum(pre15[,2])
d <- sum(po[,2])

sum1 <- (a+b+c) / 3
sum2 <- d / 1.33
unadjusted_estimate <-  (sum1 - sum2 ) / sum1  
trend_a <- (a-b)/a 
trend_b <- (b-c)/b
secular_trend <- (trend_a + trend_b) / 2
f <- ( unadjusted_estimate - secular_trend ) * 100

Y_2013_14 <- c(a,a," ", round(f,digits = 2))
Y_2014_15 <- c(b,b," "," ")
Y_2015_16 <- c(c,c," "," ")
Y_2016_17 <- c("Intervention "," "," "," ")
Y_2017_18 <- c("years "," "," "," ")
Y_2018_19 <- c(d, round(sum2,digits = 2)," "," ")

df <- data.frame(Tax_year,Y_2013_14,Y_2014_15,Y_2015_16,Y_2016_17,Y_2017_18,Y_2018_19)
colnames(df) <- c("Tax year", " 2013/14 "," 2014/15 ","  2015/16  ","  2016/17  ","  2017/18  "," 2018/19 ")
 

calculations <- c("A + B + C / 3 ", "A - B / A", "B - C / B", "Unadjusted_estimate", "Secular_trend" )
column <- c(round(sum1,digits = 2),round(trend_a,digits = 2)*100,round(trend_b,digits = 2)*100,round(unadjusted_estimate,digits = 2) *100,round(secular_trend,digits =     
                                                                                                                                                    2)*100)

df_cal <- data.frame(calculations,column)
colnames(df_cal) <-  c("Calculations", " ")

kable(df,caption = "Total number of collisions in the city of Edinburgh ", booktabs = TRUE, valign = 't') %>% kable_styling(bootstrap_options = c("hover","striped"),font_size = 15 )
kable(df_cal) %>% kable_styling(position = "center",bootstrap_options = c("basic","hover","striped"),font_size = 15 )%>%  
    footnote(general = " ", number =c("A : accidents 2013/14 ( 1 year )","B : accidents 2014/15 ( 1 year ) ","C : accidents 2015/16 ( 1 year )","D : accidents 2018/19 ( 16 months )")) 
```