---
title: "R Notebook"
output: html_notebook
---
```{r, echo=FALSE, warning=FALSE,message=FALSE}
data1 <- all

mergedDf <- data1[data1$LAYER == "20mph existing streets" & data1$Speed_limit == 30, ]
mergedDf <- mergedDf[,-2]

leaflet_map(mergedDf,edin_cons_streets)

s13 <- nrow(mergedDf[mergedDf$Date >= "2013-01-01" & mergedDf$Date <= "2013-12-31", ])
s14 <- nrow(mergedDf[mergedDf$Date >= "2014-01-01" & mergedDf$Date <= "2014-12-31", ])
s15 <- nrow(mergedDf[mergedDf$Date >= "2015-01-01" & mergedDf$Date <= "2015-12-31", ])
s16 <- nrow(mergedDf[mergedDf$Date >= "2016-01-01" & mergedDf$Date <= "2016-12-31", ])
s18 <- nrow(mergedDf[mergedDf$Date >= "2018-01-01" & mergedDf$Date <= "2018-12-31", ])
s19 <- nrow(mergedDf[mergedDf$year == "2019" , ])
data_frame(s13,s14,s15,s16,s18,s19)
```

```{r, echo=FALSE, warning=FALSE,message=FALSE}
mergedDf <- data1[data1$LAYER == "30mph" &data1$Speed_limit == 20, ]
mergedDf <- mergedDf[,-2]
leaflet_map(mergedDf,edin_cons_streets)
 
s13 <- nrow(mergedDf[mergedDf$Date >= "2013-01-01" & mergedDf$Date <= "2013-12-31", ])
s14 <- nrow(mergedDf[mergedDf$Date >= "2014-01-01" & mergedDf$Date <= "2014-12-31", ])
s15 <- nrow(mergedDf[mergedDf$Date >= "2015-01-01" & mergedDf$Date <= "2015-12-31", ])
s16 <- nrow(mergedDf[mergedDf$Date >= "2016-01-01" & mergedDf$Date <= "2016-12-31", ])
s18 <- nrow(mergedDf[mergedDf$Date >= "2018-01-01" & mergedDf$Date <= "2018-12-31", ])
s19 <- nrow(mergedDf[mergedDf$year == "2019" , ])
data_frame(s13,s14,s15,s16,s18,s19)
```


```{r, echo=FALSE, warning=FALSE,message=FALSE}
mergedDf <- data1[data1$LAYER == "20mph local streets" & data1$Speed_limit == 20, ]
leaflet_map(mergedDf,edin_cons_streets)

s13 <- nrow(mergedDf[mergedDf$Date >= "2013-01-01" & mergedDf$Date <= "2013-12-31", ])
s14 <- nrow(mergedDf[mergedDf$Date >= "2014-01-01" & mergedDf$Date <= "2014-12-31", ])
s15 <- nrow(mergedDf[mergedDf$Date >= "2015-01-01" & mergedDf$Date <= "2015-12-31", ])
s16 <- nrow(mergedDf[mergedDf$Date >= "2016-01-01" & mergedDf$Date <= "2016-12-31", ])
s18 <- nrow(mergedDf[mergedDf$Date >= "2018-01-01" & mergedDf$Date <= "2018-12-31", ])
s19 <- nrow(mergedDf[mergedDf$year == "2019" , ])
data_frame(s13,s14,s15,s16,s18,s19)
```

```{r, echo=FALSE, warning=FALSE,message=FALSE}
mergedDf <- data1[data1$LAYER == c("20mph local streets") & data1$Speed_limit == 30, ]
leaflet_map(mergedDf,edin_cons_streets)

s13 <- nrow(mergedDf[mergedDf$Date >= "2013-01-01" & mergedDf$Date <= "2013-12-31", ])
s14 <- nrow(mergedDf[mergedDf$Date >= "2014-01-01" & mergedDf$Date <= "2014-12-31", ])
s15 <- nrow(mergedDf[mergedDf$Date >= "2015-01-01" & mergedDf$Date <= "2015-12-31", ])
s16 <- nrow(mergedDf[mergedDf$Date >= "2016-01-01" & mergedDf$Date <= "2016-12-31", ])
s18 <- nrow(mergedDf[mergedDf$Date >= "2018-01-01" & mergedDf$Date <= "2018-12-31", ])
s19 <- nrow(mergedDf[mergedDf$year == "2019" , ])
data_frame(s13,s14,s15,s16,s18,s19)
```

```{r, echo=FALSE, warning=FALSE,message=FALSE}
mergedDf <- data[data$LAYER == c("20mph main streets") & data$Speed_limit == 30, ]
leaflet_map(mergedDf,edin_cons_streets)

s13 <- nrow(mergedDf[mergedDf$Date >= "2013-01-01" & mergedDf$Date <= "2013-12-31", ])
s14 <- nrow(mergedDf[mergedDf$Date >= "2014-01-01" & mergedDf$Date <= "2014-12-31", ])
s15 <- nrow(mergedDf[mergedDf$Date >= "2015-01-01" & mergedDf$Date <= "2015-12-31", ])
s16 <- nrow(mergedDf[mergedDf$Date >= "2016-01-01" & mergedDf$Date <= "2016-12-31", ])
s18 <- nrow(mergedDf[mergedDf$Date >= "2018-01-01" & mergedDf$Date <= "2018-12-31", ])
s19 <- nrow(mergedDf[mergedDf$year == "2019" , ])
data_frame(s13,s14,s15,s16,s18,s19)
```

```{r, echo=FALSE, warning=FALSE,message=FALSE}
mergedDf <- data[data$LAYER == c("20mph main streets") & data$Speed_limit == 20, ]
leaflet_map(mergedDf,edin_cons_streets)

s13 <- nrow(mergedDf[mergedDf$Date >= "2013-01-01" & mergedDf$Date <= "2013-12-31", ])
s14 <- nrow(mergedDf[mergedDf$Date >= "2014-01-01" & mergedDf$Date <= "2014-12-31", ])
s15 <- nrow(mergedDf[mergedDf$Date >= "2015-01-01" & mergedDf$Date <= "2015-12-31", ])
s16 <- nrow(mergedDf[mergedDf$Date >= "2016-01-01" & mergedDf$Date <= "2016-12-31", ])
s18 <- nrow(mergedDf[mergedDf$Date >= "2018-01-01" & mergedDf$Date <= "2018-12-31", ])
s19 <- nrow(mergedDf[mergedDf$year == "2019" , ])
data_frame(s13,s14,s15,s16,s18,s19)
```

```{r, echo=FALSE, warning=FALSE,message=FALSE}
mergedDf <- data[data$LAYER == "30mph" & data$Speed_limit == 30, ]
leaflet_map(mergedDf,edin_cons_streets)
s13 <- nrow(mergedDf[mergedDf$Date >= "2013-01-01" & mergedDf$Date <= "2013-12-31", ])
s14 <- nrow(mergedDf[mergedDf$Date >= "2014-01-01" & mergedDf$Date <= "2014-12-31", ])
s15 <- nrow(mergedDf[mergedDf$Date >= "2015-01-01" & mergedDf$Date <= "2015-12-31", ])
s16 <- nrow(mergedDf[mergedDf$Date >= "2016-01-01" & mergedDf$Date <= "2016-12-31", ])
s18 <- nrow(mergedDf[mergedDf$Date >= "2018-01-01" & mergedDf$Date <= "2018-12-31", ])
s19 <- nrow(mergedDf[mergedDf$year == "2019" , ])
data_frame(s13,s14,s15,s16,s18,s19)
```

```{r, echo=FALSE, warning=FALSE,message=FALSE}
mergedDf <- data[data$LAYER == "20mph existing streets" & data$Speed_limit == 20, ]
leaflet_map(mergedDf,edin_cons_streets)
s13 <- nrow(mergedDf[mergedDf$Date >= "2013-01-01" & mergedDf$Date <= "2013-12-31", ])
s14 <- nrow(mergedDf[mergedDf$Date >= "2014-01-01" & mergedDf$Date <= "2014-12-31", ])
s15 <- nrow(mergedDf[mergedDf$Date >= "2015-01-01" & mergedDf$Date <= "2015-12-31", ])
s16 <- nrow(mergedDf[mergedDf$Date >= "2016-01-01" & mergedDf$Date <= "2016-12-31", ])
s18 <- nrow(mergedDf[mergedDf$Date >= "2018-01-01" & mergedDf$Date <= "2018-12-31", ])
s19 <- nrow(mergedDf[mergedDf$year == "2019" , ])
data_frame(s13,s14,s15,s16,s18,s19)
```