---
title: "Untitled"
author: "edin"
date: "2/21/2020"
output: html_document
---

```{r , echo=FALSE, warning=FALSE,message=FALSE}
# Load libraries
library(rgdal)
library(leaflet)
library(tidyverse)
library(rgeos)
library(raster)
library(ggplot2)
library(sf)
library(mapview)
library(maptools)
library(sp)
library(readxl)
library(readr)
library(grid)
library(gridExtra)
library(xtable)
library(knitr)
library(kableExtra)
library(plyr)
library(RColorBrewer)

source('../functions/localSnapPointsToLines.R')

#Function for leaflet visualisations
leaflet_map <- function(final_df,edin_streets){
  crs <- CRS( "+proj=utm +zone=32 +ellps=WGS72 +units=m +no_defs")     # UTM zone = 32 N
  wgs84 <- CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0")  # long/lat
  
  #Convert data to planar projection  
  edin_streets <- spTransform(edin_streets,crs)
  coordinates(final_df) <- ~ X + Y
  
  #Convert data projections back to lat/long to plot with leaflet
  edin_streets <- spTransform(edin_streets,"+init=epsg:4326")
  
  #Same projections
  proj4string(final_df) <- proj4string(edin_streets)
  
  edin_streets <- st_as_sf(edin_streets)
  #Leaflet maps of the road network , accidents and their projections
  road_existing_20 <-edin_streets%>% filter(edin_streets$LAYER == "20mph existing streets")
  road_local_20 <- filter(edin_streets, edin_streets$LAYER == "20mph local streets")
  road_main_20 <- filter(edin_streets, edin_streets$LAYER == "20mph main streets")
  road_30 <- filter(edin_streets, edin_streets$LAYER == "30mph")
  road_part <- filter(edin_streets, edin_streets$LAYER == "Part time 20mph")
  
  
  #Visualize
  map <- leaflet() %>% addTiles() %>% addPolylines(data = edin_streets)
  
  map_near <-map %>% leaflet() %>% addTiles() %>% addMarkers(lng =final_df$X, lat = final_df$Y,
                                                             popup =paste("Accident index: ", final_df$Accident_Index, "<br>",
                                                                          "Date: ",final_df$Date ,"<br>",
                                                                          "Speed limit: ", final_df$Speed_limit ,"<br>",
                                                                          "Layer: ",final_df$LAYER ,"<br>",
                                                                          "Distance: ",final_df$snap_dist,"<br>",
                                                                          "Road type: ",final_df$Road_Type,"<br>",
                                                                          "1st road class: ",final_df$X1st_Road_Class,"<br>",
                                                                          "2nd road class: ",final_df$X2nd_Road_Class,"<br>",
                                                                          "Junction detail: ",final_df$Junction_Detail), 
                                                            group = 'incidents linked to a road')
  
  map3 <- map_near %>% addCircleMarkers(lng =final_df$Longitude , lat = final_df$Latitude,
                                        popup =paste("Accident index: ", final_df$Accident_Index, "<br>",
                                                     "Speed limit: ", final_df$Speed_limit ,"<br>",
                                                     "Date: ",final_df$Date), group = 'all incidents')
  
  
  map3 <- map3 %>% addLegend("bottomright",colors =c("#41ab5d",  "#fc4e2a", "#4eb3d3",  "#08306b","#6a51a3"),
                             labels= c("existing 20mph", "local 20mph","main 20 mph","30mph", "part time 20mph"),
                             title= "Road network",opacity = 1)
  
  map3 %>%
    setView(lng = -3.188267 , lat = 55.953251, zoom = 11)%>%
    addPolylines(data = road_existing_20, color= "#41ab5d", group = 'existing 20mph' ) %>%
    addPolylines(data = road_local_20,color= "#fc4e2a" , group = 'local 20mph' ) %>%
    addPolylines(data = road_main_20,color= "#4eb3d3" , group = 'main 20mph')%>%
    addPolylines(data = road_30,color= "#08306b" , group = '30mph') %>% 
    addPolylines(data = road_part,color= "#6a51a3" , group = 'part time 20mph')%>%
    addLayersControl(overlayGroups = c( 'existing 20mph','local 20mph','main 20mph','30mph','part time 20mph',
                                        'incidents linked to a road', 'all incidents'),options = layersControlOptions(collapsed = FALSE))
}


leaflet_map_compararison <- function(final_df,edin_streets){
  crs <- CRS( "+proj=utm +zone=32 +ellps=WGS72 +units=m +no_defs")     # UTM zone = 32 N
  wgs84 <- CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0")  # long/lat
  
  #Convert data to planar projection  
  edin_streets <- spTransform(edin_streets,crs)
  coordinates(final_df) <- ~ X + Y
  
  #Convert data projections back to lat/long to plot with leaflet
  edin_streets <- spTransform(edin_streets,"+init=epsg:4326")
  
  #Same projections
  proj4string(final_df) <- proj4string(edin_streets)
  
  edin_streets <- st_as_sf(edin_streets)
  #Leaflet maps of the road network , accidents and their projections
  road_existing_20 <-edin_streets%>% filter(edin_streets$LAYER == "20mph existing streets")
  road_local_20 <- filter(edin_streets, edin_streets$LAYER == "20mph local streets")
  road_main_20 <- filter(edin_streets, edin_streets$LAYER == "20mph main streets")
  road_30 <- filter(edin_streets, edin_streets$LAYER == "30mph")
  road_part <- filter(edin_streets, edin_streets$LAYER == "Part time 20mph")
  
  
  #Visualize
  map <- leaflet() %>% addTiles() %>% addPolylines(data = edin_streets)
  
  map_near <-map %>% leaflet() %>% addTiles() %>% addMarkers(lng = final_df$X, lat = final_df$Y,
                                                             popup = paste("Accident index: ", final_df$Accident_Index, "<br>",
                                                                          "Date: ",final_df$Date ,"<br>",
                                                                          "Speed limit: ", final_df$Speed_limit ,"<br>",
                                                                          "Layer before: ",final_df$LAYER.x ,"<br>",
                                                                          "Layer after: ",final_df$LAYER.y ,"<br>",
                                                                          "Distance before: ",final_df$snap_dist_before,"<br>",
                                                                          "Distance after: ",final_df$snap_dist,"<br>",
                                                                          "Road type: ",final_df$Road_Type,"<br>",
                                                                          "1st road class: ",final_df$X1st_Road_Class,"<br>",
                                                                          "2nd road class: ",final_df$X2nd_Road_Class,"<br>",
                                                                          "Junction detail: ",final_df$Junction_Detail), 
                                                            group = 'incidents linked to a road')
  
  map3 <- map_near %>% addCircleMarkers(lng = final_df$Longitude , lat = final_df$Latitude,
                                        popup = paste("Accident index: ", final_df$Accident_Index, "<br>",
                                                     "Speed limit: ", final_df$Speed_limit ,"<br>",
                                                     "Date: ",final_df$Date), group = 'all incidents')
  
  
  map3 <- map3 %>% addLegend("bottomright",colors = c("#41ab5d",  "#fc4e2a", "#4eb3d3",  "#08306b","#6a51a3"),
                             labels= c("existing 20mph", "local 20mph","main 20 mph","30mph", "part time 20mph"),
                             title= "Road network",opacity = 1)
  
  map3 %>%
    setView(lng = -3.188267 , lat = 55.953251, zoom = 11)%>%
    addPolylines(data = road_existing_20, color = "#41ab5d", group = 'existing 20mph' ) %>%
    addPolylines(data = road_local_20,color = "#fc4e2a" , group = 'local 20mph' ) %>%
    addPolylines(data = road_main_20,color = "#4eb3d3" , group = 'main 20mph')%>%
    addPolylines(data = road_30,color = "#08306b" , group = '30mph') %>% 
    addPolylines(data = road_part,color = "#6a51a3" , group = 'part time 20mph')%>%
    addLayersControl(overlayGroups = c( 'existing 20mph','local 20mph','main 20mph','30mph','part time 20mph',
                                        'incidents linked to a road', 'all incidents'), options = layersControlOptions(collapsed = FALSE))
}

#2.Function for deleting Na points
delete_na <- function(data, desiredCols) {
  completeVec <- complete.cases(data[, desiredCols])
  return(data[completeVec, ])
}

nearest_line <-function(df,road_net){
  #Create planar(cartesian) projection 
  crs <- CRS( "+proj=utm +zone=32 +ellps=WGS72 +units=m +no_defs")     # UTM zone = 32 N
  wgs84 <- CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0")  # long/lat
  
  #Convert data to planar projection  
  road_net <- spTransform(road_net,crs)
  coords = data.frame(df$Longitude,df$Latitude)
  df <-  spTransform(SpatialPointsDataFrame(coords = coords, proj4string = wgs84, data = df), crs)
  
  #Make sure our data have same projections
  proj4string(df) <- proj4string(road_net)
  
  #Find nearest line with maxDist=6m 
  nearest_line_sp <- localSnapPointsToLines(df, road_net, maxDist = 10, withAttrs = TRUE)
  
  return(nearest_line_sp)
}
```


```{r , echo=FALSE, warning=FALSE,message=FALSE}
dir_path <- "../data"
data <- read_csv(paste0(dir_path, "/merged_data.csv"))

data$X1st_Road_Class[data$X1st_Road_Class == 0] <- "Not a junction or within 20meters"
data$X1st_Road_Class[data$X1st_Road_Class == 1] <- "Motorway"
data$X1st_Road_Class[data$X1st_Road_Class == 2] <- "A(M)"
data$X1st_Road_Class[data$X1st_Road_Class == 3] <- "A"
data$X1st_Road_Class[data$X1st_Road_Class == 4] <- "B"
data$X1st_Road_Class[data$X1st_Road_Class == 5] <- "C"
data$X1st_Road_Class[data$X1st_Road_Class == 6] <- "Unclassified"

data$X2nd_Road_Class[data$X2nd_Road_Class == 0] <- "Not a junction or within 20meters"
data$X2nd_Road_Class[data$X2nd_Road_Class == 1] <- "Motorway"
data$X2nd_Road_Class[data$X2nd_Road_Class == 2] <- "A(M)"
data$X2nd_Road_Class[data$X2nd_Road_Class == 3] <- "A"
data$X2nd_Road_Class[data$X2nd_Road_Class == 4] <- "B"
data$X2nd_Road_Class[data$X2nd_Road_Class == 5] <- "C"
data$X2nd_Road_Class[data$X2nd_Road_Class == 6] <- "unclassified"

data$Junction_Detail[data$Junction_Detail == 0] <- "Not a junction or within 20meters"
data$Junction_Detail[data$Junction_Detail == 1] <- "Roundabout"
data$Junction_Detail[data$Junction_Detail == 2] <- "Mini-roundabout"
data$Junction_Detail[data$Junction_Detail == 3] <- "T or staggered junction"
data$Junction_Detail[data$Junction_Detail == 5] <- "Slip road"
data$Junction_Detail[data$Junction_Detail == 6] <- "Crossroads"
data$Junction_Detail[data$Junction_Detail == 7] <- "More than 4 arms(not roundabout"
data$Junction_Detail[data$Junction_Detail == 8] <- "Private drive or entrance"
data$Junction_Detail[data$Junction_Detail == 9] <- "Other junction"
data$Junction_Detail[data$Junction_Detail == -1] <- "data missing"

data$Road_Type[data$Road_Type == 1] <- "Roundabout"
data$Road_Type[data$Road_Type == 2] <- "One way street"
data$Road_Type[data$Road_Type == 3] <- "Dual carriageway"
data$Road_Type[data$Road_Type == 6] <- "single carriageway"
data$Road_Type[data$Road_Type == 7] <- "slip road"
data$Road_Type[data$Road_Type == 9] <- "unknown"
data$Road_Type[data$Road_Type == 12] <- "One way street/slip road"
data$Road_Type[data$Road_Type == -1] <- "data missing"


#2.Gis 
#Read geodatabase for Edinburgh
#Path
```


```{r , echo=FALSE, warning=FALSE,message=FALSE}
gdb_path <- paste0(dir_path, "/20mph.gdb")
gdb_layers <- ogrListLayers(gdb_path)

#Read shapefile
edin_cons_streets <- readOGR(dsn = gdb_path,layer="Consultation20mphStreets", verbose = FALSE)
#Put ID column as variable 
edin_cons_streets@data <-rowid_to_column(edin_cons_streets@data, "ID")
#Transform to long/lat
edin_cons_streets <- spTransform(edin_cons_streets, "+init=epsg:4326")
```

> layer =  existing 20mph
> speed limit = 30mph
NEW

```{r, echo=FALSE, warning=FALSE,message=FALSE}
#exclude 20mph existing streets and link again accidents to the remaining layers
#"20mph local streets","20mph main streets","30mph","Part time 20mph","20mph existing streets"
#data1 <- data
#data1 <-data [data$year == "2019",]
data1 <- delete_na(data[data$X2nd_Road_Class != "-1", ],"Accident_Index")
summary <- aggregate(Accident_Index~X1st_Road_Class + LAYER ,data1,length)
summary1 <- aggregate(Accident_Index~X1st_Road_Class,data1,length)
summary2 <- aggregate(Accident_Index~X1st_Road_Class ,data1,length)
```


```{r, echo=FALSE, warning=FALSE,message=FALSE}
mergedDf <- data1[data1$LAYER == "20mph existing streets" & data1$Speed_limit == 30, ]
mergedDf <- mergedDf[,-2]
mergedDf <- rename(mergedDf,c("snap_dist" = "snap_dist_before"))

network_existing <- edin_cons_streets[edin_cons_streets@data$LAYER  %in% c( "20mph local streets","20mph main streets","30mph","Part time 20mph"),]

new_lines_existing <- nearest_line(mergedDf,network_existing)
new_nearest_road <- spTransform(new_lines_existing,"+init=epsg:4326")
new_nearest_road <-new_lines_existing@data
new_nearest_road <- unique(merge(new_nearest_road,network_existing@data,by.x = "nearest_line_id" ,by.y = "ID"))


df1 <- new_nearest_road
df1 <- df1[,-c(38,41,42,44,46,48)]

```

> layer = 30mph 
>speed limit = 20mph
>NEW

```{r, echo=FALSE, warning=FALSE,message=FALSE}
network_30mph <- edin_cons_streets[edin_cons_streets@data$LAYER  %in% c( "20mph local streets","20mph main streets","20mph existing streets","Part time 20mph"),]
mergedDf <- data1[data1$LAYER == "30mph" &data1$Speed_limit == 20, ]
mergedDf <- mergedDf[,-2]
mergedDf <- rename(mergedDf,c("snap_dist" = "snap_dist_before"))

new_lines_30mph <- nearest_line(mergedDf,network_30mph)
new_nearest_road_30mph <- spTransform(new_lines_30mph,"+init=epsg:4326")
new_nearest_road_30mph <-new_lines_30mph@data
new_nearest_road_30mph <- unique(merge(new_nearest_road_30mph,network_30mph@data,by.x = "nearest_line_id" ,by.y = "ID"))

df2 <- new_nearest_road_30mph
df2 <- df2[,-c(38,41,42,44,46,48)]
```

>layer = local 20mph
>Speed limit = 20
>NEW

```{r,echo=FALSE, warning=FALSE,message=FALSE}
network_20mphlocal <- edin_cons_streets[edin_cons_streets@data$LAYER  %in% c( "30mph", "20mph main streets","20mph existing streets","Part time 20mph"),]
mergedDf <- data1[data1$LAYER == c("20mph local streets")  & data1$Speed_limit == 20, ]
#mergedDf <- mergedDf[mergedDf$Date >="2013-07-31" & mergedDf$Date <= "2016-07-31" , ]
mergedDf <- mergedDf[,-2]
mergedDf <- rename(mergedDf,c("snap_dist" = "snap_dist_before"))

new_lines_20mphlocal <- nearest_line(mergedDf,network_20mphlocal)
new_nearest_road_20mphlocal <- spTransform(new_lines_20mphlocal,"+init=epsg:4326")
new_nearest_road_20mphlocal <-new_lines_20mphlocal@data
new_nearest_road_20mphlocal <- unique(merge(new_nearest_road_20mphlocal,network_20mphlocal@data,by.x = "nearest_line_id" ,by.y = "ID"))

df3 <- new_nearest_road_20mphlocal
df3 <- df3[,-c(38,41,42,44,46,48)]
```

>layer = local 20mph
>Speed limit = 30
>NEW

```{r, echo=FALSE, warning=FALSE,message=FALSE}
network_20mphlocal <- edin_cons_streets[edin_cons_streets@data$LAYER  %in% c( "30mph","20mph main streets","20mph existing streets","Part time 20mph"),]
mergedDf <- data1[data1$LAYER == c("20mph local streets") & data1$Speed_limit == 30, ]
#mergedDf <- mergedDf[mergedDf$Date >="2018-01-01" & mergedDf$Date <= "2019-07-31" , ]
mergedDf <- mergedDf[,-2]
mergedDf <- rename(mergedDf,c("snap_dist" = "snap_dist_before"))

new_lines_20mphlocal <- nearest_line(mergedDf,network_20mphlocal)
new_nearest_road_20mphlocal <- spTransform(new_lines_20mphlocal,"+init=epsg:4326")
new_nearest_road_20mphlocal <-new_lines_20mphlocal@data
new_nearest_road_20mphlocal <- unique(merge(new_nearest_road_20mphlocal,network_20mphlocal@data,by.x = "nearest_line_id" ,by.y = "ID"))

df4 <- new_nearest_road_20mphlocal
df4 <- df4[,-c(38,41,42,44,46,48)]
```

>layer = main 20mph
>Speed limit = 30
>NEW

```{r, echo=FALSE, warning=FALSE,message=FALSE}
network_20mphmain <- edin_cons_streets[edin_cons_streets@data$LAYER  %in% c( "30mph","20mph local streets","20mph existing streets","Part time 20mph"),]
mergedDf <- data1[data1$LAYER == c("20mph main streets") & data1$Speed_limit == 30, ]
#mergedDf <- mergedDf[mergedDf$Date >="2018-01-01" & mergedDf$Date <= "2019-07-31" , ]
mergedDf <- mergedDf[,-2]
mergedDf <- rename(mergedDf,c("snap_dist" = "snap_dist_before"))

new_lines_20mphmain <- nearest_line(mergedDf,network_20mphmain)
new_nearest_road_20mphmain <- spTransform(new_lines_20mphmain,"+init=epsg:4326")
new_nearest_road_20mphmain <-new_lines_20mphmain@data
new_nearest_road_20mphmain <- unique(merge(new_nearest_road_20mphmain,network_20mphlocal@data,by.x = "nearest_line_id" ,by.y = "ID"))

df5 <- new_nearest_road_20mphmain
df5 <- df5[,-c(38,41,42,44,46,48)]
```

> layer = main 20mph
> Speed limit = 20
NEW

```{r}
network_20mphmain <- edin_cons_streets[edin_cons_streets@data$LAYER  %in% c( "30mph","20mph local streets","20mph existing streets","Part time 20mph"),]
mergedDf <- data1[data1$LAYER == c("20mph main streets") & data1$Speed_limit == 20, ]
#mergedDf <- mergedDf[mergedDf$Date >="2013-07-31" & mergedDf$Date <= "2016-07-31" , ]
mergedDf <- mergedDf[,-2]
mergedDf <- rename(mergedDf,c("snap_dist" = "snap_dist_before"))

new_lines_20mphmain <- nearest_line(mergedDf,network_20mphmain)
new_nearest_road_20mphmain <- spTransform(new_lines_20mphmain,"+init=epsg:4326")
new_nearest_road_20mphmain <-new_lines_20mphmain@data
new_nearest_road_20mphmain <- unique(merge(new_nearest_road_20mphmain,network_20mphlocal@data,by.x = "nearest_line_id" ,by.y = "ID"))

df6 <- new_nearest_road_20mphmain
df6 <- df6[,-c(38,41,42,44,46,48)]
```

> layer = existing  20mph
> Speed limit = 20

```{r, echo=FALSE, warning=FALSE,message=FALSE}
network_20mphexisting <- edin_cons_streets[edin_cons_streets@data$LAYER  %in% c( "30mph","20mph local streets","20mph main streets","Part time 20mph"),]
mergedDf <- data1[data1$LAYER == c("20mph existing streets") & data1$Speed_limit == 20, ]
#mergedDf <- mergedDf[mergedDf$Date >="2013-07-31" & mergedDf$Date <= "2016-07-31" , ]
mergedDf <- mergedDf[,-2]
mergedDf <- rename(mergedDf,c("snap_dist" = "snap_dist_before"))

new_lines_20mphexisting <- nearest_line(mergedDf,network_20mphexisting)
new_nearest_road_20mphexisting <- spTransform(new_lines_20mphexisting,"+init=epsg:4326")
new_nearest_road_20mphexisting <-new_lines_20mphexisting@data
new_nearest_road_20mphexisting <- unique(merge(new_nearest_road_20mphexisting,network_20mphexisting@data,by.x = "nearest_line_id" ,by.y = "ID"))

df7 <- new_nearest_road_20mphexisting
df7 <- df7[,-c(38,41,42,44,46,48)]
```

> layer = 30mph
> Speed limit = 30

```{r, echo=FALSE, warning=FALSE,message=FALSE}
network_30mph <- edin_cons_streets[edin_cons_streets@data$LAYER  %in% c( "20mph local streets","20mph main streets","20mph existing streets","Part time 20mph"),]
mergedDf <- data1[data1$LAYER == "30mph" & data1$Speed_limit == 30, ]
mergedDf <- mergedDf[,-2]
mergedDf <- rename(mergedDf,c("snap_dist" = "snap_dist_before"))

new_lines_30mph <- nearest_line(mergedDf,network_30mph)
new_nearest_road_30mph <- spTransform(new_lines_30mph,"+init=epsg:4326")
new_nearest_road_30mph <-new_lines_30mph@data
new_nearest_road_30mph <- unique(merge(new_nearest_road_30mph,network_30mph@data,by.x = "nearest_line_id" ,by.y = "ID"))

df8 <- new_nearest_road_30mph
df8 <- df8[,-c(38,41,42,44,46,48)]
```

>new data

```{r, echo=FALSE, warning=FALSE,message=FALSE}

#changed_2019 <- rbind(df1,df2,df3,df4,df5,df6,df7,df8)
changed <- rbind(df1,df2,df3,df4,df5,df6,df7,df8)

changed <- rbind(changed,changed_2019)
changed <- 
leaflet_map_compararison(changed,edin_cons_streets)

changed1 <- delete_na(changed[changed$X1st_Road_Class != "Unclassified",],"Accident_Index")
changed1$LAYER.x <- changed1$LAYER.y
changed1 <- rename(changed1,c("LAYER.x"="LAYER"))
not_changed <- delete_na(data[!(data$Accident_Index %in% changed1$Accident_Index),],"Accident_Index")
all <- rbind.fill(changed1,not_changed)
```


```{r}
data1 <- all

mergedDf <- data1[data1$LAYER == "20mph existing streets" & data1$Speed_limit == 30, ]
mergedDf <- mergedDf[,-2]

leaflet_map(mergedDf,edin_cons_streets)

s13 <- nrow(mergedDf[mergedDf$Date >= "2013-01-01" & mergedDf$Date <= "2013-12-31", ])
s14 <- nrow(mergedDf[mergedDf$Date >= "2014-01-01" & mergedDf$Date <= "2014-12-31", ])
s15 <- nrow(mergedDf[mergedDf$Date >= "2015-01-01" & mergedDf$Date <= "2015-12-31", ])
s16 <- nrow(mergedDf[mergedDf$Date >= "2016-01-01" & mergedDf$Date <= "2016-12-31", ])
s18 <- nrow(mergedDf[mergedDf$Date >= "2018-01-01" & mergedDf$Date <= "2018-12-31", ])
s19 <- nrow(mergedDf[mergedDf$year == "2019" , ])
data_frame(s13,s14,s15,s16,s18,s19)
```

```{r}
mergedDf <- data1[data1$LAYER == "30mph" &data1$Speed_limit == 20, ]
mergedDf <- mergedDf[,-2]
leaflet_map(mergedDf,edin_cons_streets)
 
s13 <- nrow(mergedDf[mergedDf$Date >= "2013-01-01" & mergedDf$Date <= "2013-12-31", ])
s14 <- nrow(mergedDf[mergedDf$Date >= "2014-01-01" & mergedDf$Date <= "2014-12-31", ])
s15 <- nrow(mergedDf[mergedDf$Date >= "2015-01-01" & mergedDf$Date <= "2015-12-31", ])
s16 <- nrow(mergedDf[mergedDf$Date >= "2016-01-01" & mergedDf$Date <= "2016-12-31", ])
s18 <- nrow(mergedDf[mergedDf$Date >= "2018-01-01" & mergedDf$Date <= "2018-12-31", ])
s19 <- nrow(mergedDf[mergedDf$year == "2019" , ])
data_frame(s13,s14,s15,s16,s18,s19)
```


```{r}
mergedDf <- data1[data1$LAYER == "20mph local streets" & data1$Speed_limit == 20, ]
leaflet_map(mergedDf,edin_cons_streets)

s13 <- nrow(mergedDf[mergedDf$Date >= "2013-01-01" & mergedDf$Date <= "2013-12-31", ])
s14 <- nrow(mergedDf[mergedDf$Date >= "2014-01-01" & mergedDf$Date <= "2014-12-31", ])
s15 <- nrow(mergedDf[mergedDf$Date >= "2015-01-01" & mergedDf$Date <= "2015-12-31", ])
s16 <- nrow(mergedDf[mergedDf$Date >= "2016-01-01" & mergedDf$Date <= "2016-12-31", ])
s18 <- nrow(mergedDf[mergedDf$Date >= "2018-01-01" & mergedDf$Date <= "2018-12-31", ])
s19 <- nrow(mergedDf[mergedDf$year == "2019" , ])
data_frame(s13,s14,s15,s16,s18,s19)
```

```{r}
mergedDf <- data1[data1$LAYER == c("20mph local streets") & data1$Speed_limit == 30, ]
leaflet_map(mergedDf,edin_cons_streets)

s13 <- nrow(mergedDf[mergedDf$Date >= "2013-01-01" & mergedDf$Date <= "2013-12-31", ])
s14 <- nrow(mergedDf[mergedDf$Date >= "2014-01-01" & mergedDf$Date <= "2014-12-31", ])
s15 <- nrow(mergedDf[mergedDf$Date >= "2015-01-01" & mergedDf$Date <= "2015-12-31", ])
s16 <- nrow(mergedDf[mergedDf$Date >= "2016-01-01" & mergedDf$Date <= "2016-12-31", ])
s18 <- nrow(mergedDf[mergedDf$Date >= "2018-01-01" & mergedDf$Date <= "2018-12-31", ])
s19 <- nrow(mergedDf[mergedDf$year == "2019" , ])
data_frame(s13,s14,s15,s16,s18,s19)
```

```{r}
mergedDf <- data[data$LAYER == c("20mph main streets") & data$Speed_limit == 30, ]
leaflet_map(mergedDf,edin_cons_streets)

s13 <- nrow(mergedDf[mergedDf$Date >= "2013-01-01" & mergedDf$Date <= "2013-12-31", ])
s14 <- nrow(mergedDf[mergedDf$Date >= "2014-01-01" & mergedDf$Date <= "2014-12-31", ])
s15 <- nrow(mergedDf[mergedDf$Date >= "2015-01-01" & mergedDf$Date <= "2015-12-31", ])
s16 <- nrow(mergedDf[mergedDf$Date >= "2016-01-01" & mergedDf$Date <= "2016-12-31", ])
s18 <- nrow(mergedDf[mergedDf$Date >= "2018-01-01" & mergedDf$Date <= "2018-12-31", ])
s19 <- nrow(mergedDf[mergedDf$year == "2019" , ])
data_frame(s13,s14,s15,s16,s18,s19)
```

```{r}
mergedDf <- data[data$LAYER == c("20mph main streets") & data$Speed_limit == 20, ]
leaflet_map(mergedDf,edin_cons_streets)

s13 <- nrow(mergedDf[mergedDf$Date >= "2013-01-01" & mergedDf$Date <= "2013-12-31", ])
s14 <- nrow(mergedDf[mergedDf$Date >= "2014-01-01" & mergedDf$Date <= "2014-12-31", ])
s15 <- nrow(mergedDf[mergedDf$Date >= "2015-01-01" & mergedDf$Date <= "2015-12-31", ])
s16 <- nrow(mergedDf[mergedDf$Date >= "2016-01-01" & mergedDf$Date <= "2016-12-31", ])
s18 <- nrow(mergedDf[mergedDf$Date >= "2018-01-01" & mergedDf$Date <= "2018-12-31", ])
s19 <- nrow(mergedDf[mergedDf$year == "2019" , ])
data_frame(s13,s14,s15,s16,s18,s19)
```

```{r}
mergedDf <- data[data$LAYER == "30mph" & data$Speed_limit == 30, ]
leaflet_map(mergedDf,edin_cons_streets)
s13 <- nrow(mergedDf[mergedDf$Date >= "2013-01-01" & mergedDf$Date <= "2013-12-31", ])
s14 <- nrow(mergedDf[mergedDf$Date >= "2014-01-01" & mergedDf$Date <= "2014-12-31", ])
s15 <- nrow(mergedDf[mergedDf$Date >= "2015-01-01" & mergedDf$Date <= "2015-12-31", ])
s16 <- nrow(mergedDf[mergedDf$Date >= "2016-01-01" & mergedDf$Date <= "2016-12-31", ])
s18 <- nrow(mergedDf[mergedDf$Date >= "2018-01-01" & mergedDf$Date <= "2018-12-31", ])
s19 <- nrow(mergedDf[mergedDf$year == "2019" , ])
data_frame(s13,s14,s15,s16,s18,s19)
```

```{r}
mergedDf <- data[data$LAYER == "20mph existing streets" & data$Speed_limit == 20, ]
leaflet_map(mergedDf,edin_cons_streets)
s13 <- nrow(mergedDf[mergedDf$Date >= "2013-01-01" & mergedDf$Date <= "2013-12-31", ])
s14 <- nrow(mergedDf[mergedDf$Date >= "2014-01-01" & mergedDf$Date <= "2014-12-31", ])
s15 <- nrow(mergedDf[mergedDf$Date >= "2015-01-01" & mergedDf$Date <= "2015-12-31", ])
s16 <- nrow(mergedDf[mergedDf$Date >= "2016-01-01" & mergedDf$Date <= "2016-12-31", ])
s18 <- nrow(mergedDf[mergedDf$Date >= "2018-01-01" & mergedDf$Date <= "2018-12-31", ])
s19 <- nrow(mergedDf[mergedDf$year == "2019" , ])
data_frame(s13,s14,s15,s16,s18,s19)
```



```{r}
mergedDf <- all
mergedDf$LAYER <- as.character((mergedDf$LAYER)) 
mergedDf$Date <- as.character(mergedDf$Date)
pre13 <- count_post(mergedDf[mergedDf$Date >= "2013-07-31" & mergedDf$Date <= "2014-07-30" ,])
pre14 <- count_post(mergedDf[mergedDf$Date >= "2014-07-31" & mergedDf$Date <= "2015-07-30" ,])
pre15 <- count_post(mergedDf[mergedDf$Date >= "2015-07-31" & mergedDf$Date <= "2016-07-30" ,])
pre <- count_pre(mergedDf[mergedDf$Date >= "2013-07-31" & mergedDf$Date <= "2016-07-30" ,])
post <- count_pre(mergedDf[mergedDf$Date >= "2018-03-06" & mergedDf$Date <= "2019-06-31" ,])
po <- count_post(mergedDf[mergedDf$Date >= "2018-03-06" & mergedDf$Date <= "2019-06-31" ,])
```

```{r}
table_annual(pre,post)
```

