---
  title: "Edinburgh"
date: "2/6/2020"
output: html_document
---

  
```{r , echo=FALSE, warning=FALSE,message=FALSE}
# Load libraries
library(rgdal)
library(leaflet)
library(tidyverse)
library(rgeos)
library(raster)
library(ggplot2)
library(sf)
library(mapview)
library(maptools)
library(sp)
library(readxl)
library(readr)
library(grid)
library(gridExtra)
library(xtable)
library(knitr)
library(kableExtra)
library(plyr)
library(RColorBrewer)

source('../functions/localSnapPointsToLines.R')

#Function for leaflet visualisations
leaflet_map <- function(final_df,edin_streets){
  crs <- CRS( "+proj=utm +zone=32 +ellps=WGS72 +units=m +no_defs")     # UTM zone = 32 N
  wgs84 <- CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0")  # long/lat
  
  #Convert data to planar projection  
  edin_streets <- spTransform(edin_streets,crs)
  coordinates(final_df) <- ~ X + Y
  
  #Convert data projections back to lat/long to plot with leaflet
  edin_streets <- spTransform(edin_streets,"+init=epsg:4326")
  
  #Same projections
  proj4string(final_df) <- proj4string(edin_streets)
  
  edin_streets <- st_as_sf(edin_streets)
  #Leaflet maps of the road network , accidents and their projections
  road_existing_20 <-edin_streets%>% filter(edin_streets$LAYER == "20mph existing streets")
  road_local_20 <- filter(edin_streets, edin_streets$LAYER == "20mph local streets")
  road_main_20 <- filter(edin_streets, edin_streets$LAYER == "20mph main streets")
  road_30 <- filter(edin_streets, edin_streets$LAYER == "30mph")
  road_part <- filter(edin_streets, edin_streets$LAYER == "Part time 20mph")
  
  
  #Visualize
  map <- leaflet() %>% addTiles() %>% addPolylines(data = edin_streets)
  
  map_near <-map %>% leaflet() %>% addTiles() %>% addMarkers(lng =final_df$X, lat = final_df$Y,
                                                             popup =paste("Accident index: ", final_df$Accident_Index, "<br>",
                                                                          "Date: ",final_df$Date ,"<br>",
                                                                          "Speed limit: ", final_df$Speed_limit ,"<br>",
                                                                          "Layer: ",final_df$LAYER ,"<br>",
                                                                          "Distance: ",final_df$snap_dist,"<br>",
                                                                          "Road type: ",final_df$Road_Type,"<br>",
                                                                          "1st road class: ",final_df$X1st_Road_Class,"<br>",
                                                                          "2nd road class: ",final_df$X2nd_Road_Class,"<br>",
                                                                          "Junction detail: ",final_df$Junction_Detail), 
                                                            group = 'incidents linked to a road')
  
  map3 <- map_near %>% addCircleMarkers(lng =final_df$Longitude , lat = final_df$Latitude,
                                        popup =paste("Accident index: ", final_df$Accident_Index, "<br>",
                                                     "Speed limit: ", final_df$Speed_limit ,"<br>",
                                                     "Date: ",final_df$Date), group = 'all incidents')
  
  
  map3 <- map3 %>% addLegend("bottomright",colors =c("#41ab5d",  "#fc4e2a", "#4eb3d3",  "#08306b","#6a51a3"),
                             labels= c("existing 20mph", "local 20mph","main 20 mph","30mph", "part time 20mph"),
                             title= "Road network",opacity = 1)
  
  map3 %>%
    setView(lng = -3.188267 , lat = 55.953251, zoom = 11)%>%
    addPolylines(data = road_existing_20, color= "#41ab5d", group = 'existing 20mph' ) %>%
    addPolylines(data = road_local_20,color= "#fc4e2a" , group = 'local 20mph' ) %>%
    addPolylines(data = road_main_20,color= "#4eb3d3" , group = 'main 20mph')%>%
    addPolylines(data = road_30,color= "#08306b" , group = '30mph') %>% 
    addPolylines(data = road_part,color= "#6a51a3" , group = 'part time 20mph')%>%
    addLayersControl(overlayGroups = c( 'existing 20mph','local 20mph','main 20mph','30mph','part time 20mph',
                                        'incidents linked to a road', 'all incidents'),options = layersControlOptions(collapsed = FALSE))
}


leaflet_map_compararison <- function(final_df,edin_streets){
  crs <- CRS( "+proj=utm +zone=32 +ellps=WGS72 +units=m +no_defs")     # UTM zone = 32 N
  wgs84 <- CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0")  # long/lat
  
  #Convert data to planar projection  
  edin_streets <- spTransform(edin_streets,crs)
  coordinates(final_df) <- ~ X + Y
  
  #Convert data projections back to lat/long to plot with leaflet
  edin_streets <- spTransform(edin_streets,"+init=epsg:4326")
  
  #Same projections
  proj4string(final_df) <- proj4string(edin_streets)
  
  edin_streets <- st_as_sf(edin_streets)
  #Leaflet maps of the road network , accidents and their projections
  road_existing_20 <-edin_streets%>% filter(edin_streets$LAYER == "20mph existing streets")
  road_local_20 <- filter(edin_streets, edin_streets$LAYER == "20mph local streets")
  road_main_20 <- filter(edin_streets, edin_streets$LAYER == "20mph main streets")
  road_30 <- filter(edin_streets, edin_streets$LAYER == "30mph")
  road_part <- filter(edin_streets, edin_streets$LAYER == "Part time 20mph")
  
  
  #Visualize
  map <- leaflet() %>% addTiles() %>% addPolylines(data = edin_streets)
  
  map_near <-map %>% leaflet() %>% addTiles() %>% addMarkers(lng = final_df$X, lat = final_df$Y,
                                                             popup = paste("Accident index: ", final_df$Accident_Index, "<br>",
                                                                          "Date: ",final_df$Date ,"<br>",
                                                                          "Speed limit: ", final_df$Speed_limit ,"<br>",
                                                                          "Layer before: ",final_df$LAYER.x ,"<br>",
                                                                          "Layer after: ",final_df$LAYER.y ,"<br>",
                                                                          "Distance before: ",final_df$snap_dist_before,"<br>",
                                                                          "Distance after: ",final_df$snap_dist,"<br>",
                                                                          "Road type: ",final_df$Road_Type,"<br>",
                                                                          "1st road class: ",final_df$X1st_Road_Class,"<br>",
                                                                          "2nd road class: ",final_df$X2nd_Road_Class,"<br>",
                                                                          "Junction detail: ",final_df$Junction_Detail), 
                                                            group = 'incidents linked to a road')
  
  map3 <- map_near %>% addCircleMarkers(lng = final_df$Longitude , lat = final_df$Latitude,
                                        popup = paste("Accident index: ", final_df$Accident_Index, "<br>",
                                                     "Speed limit: ", final_df$Speed_limit ,"<br>",
                                                     "Date: ",final_df$Date), group = 'all incidents')
  
  
  map3 <- map3 %>% addLegend("bottomright",colors = c("#41ab5d",  "#fc4e2a", "#4eb3d3",  "#08306b","#6a51a3"),
                             labels= c("existing 20mph", "local 20mph","main 20 mph","30mph", "part time 20mph"),
                             title= "Road network",opacity = 1)
  
  map3 %>%
    setView(lng = -3.188267 , lat = 55.953251, zoom = 11)%>%
    addPolylines(data = road_existing_20, color = "#41ab5d", group = 'existing 20mph' ) %>%
    addPolylines(data = road_local_20,color = "#fc4e2a" , group = 'local 20mph' ) %>%
    addPolylines(data = road_main_20,color = "#4eb3d3" , group = 'main 20mph')%>%
    addPolylines(data = road_30,color = "#08306b" , group = '30mph') %>% 
    addPolylines(data = road_part,color = "#6a51a3" , group = 'part time 20mph')%>%
    addLayersControl(overlayGroups = c( 'existing 20mph','local 20mph','main 20mph','30mph','part time 20mph',
                                        'incidents linked to a road', 'all incidents'), options = layersControlOptions(collapsed = FALSE))
}

#2.Function for deleting Na points
delete_na <- function(data, desiredCols) {
  completeVec <- complete.cases(data[, desiredCols])
  return(data[completeVec, ])
}

nearest_line <-function(df,road_net){
  #Create planar(cartesian) projection 
  crs <- CRS( "+proj=utm +zone=32 +ellps=WGS72 +units=m +no_defs")     # UTM zone = 32 N
  wgs84 <- CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0")  # long/lat
  
  #Convert data to planar projection  
  road_net <- spTransform(road_net,crs)
  coords = data.frame(df$Longitude,df$Latitude)
  df <-  spTransform(SpatialPointsDataFrame(coords = coords, proj4string = wgs84, data = df), crs)
  
  #Make sure our data have same projections
  proj4string(df) <- proj4string(road_net)
  
  #Find nearest line with maxDist=6m 
  nearest_line_sp <- localSnapPointsToLines(df, road_net, maxDist = 10, withAttrs = TRUE)
  
  return(nearest_line_sp)
}
```


```{r , echo=FALSE, warning=FALSE,message=FALSE}
dir_path <- "../data"
data <- read_csv(paste0(dir_path, "/merged_data.csv"))

data$X1st_Road_Class[data$X1st_Road_Class == 0] <- "Not a junction or within 20meters"
data$X1st_Road_Class[data$X1st_Road_Class == 1] <- "Motorway"
data$X1st_Road_Class[data$X1st_Road_Class == 2] <- "A(M)"
data$X1st_Road_Class[data$X1st_Road_Class == 3] <- "A"
data$X1st_Road_Class[data$X1st_Road_Class == 4] <- "B"
data$X1st_Road_Class[data$X1st_Road_Class == 5] <- "C"
data$X1st_Road_Class[data$X1st_Road_Class == 6] <- "Unclassified"

data$X2nd_Road_Class[data$X2nd_Road_Class == 0] <- "Not a junction or within 20meters"
data$X2nd_Road_Class[data$X2nd_Road_Class == 1] <- "Motorway"
data$X2nd_Road_Class[data$X2nd_Road_Class == 2] <- "A(M)"
data$X2nd_Road_Class[data$X2nd_Road_Class == 3] <- "A"
data$X2nd_Road_Class[data$X2nd_Road_Class == 4] <- "B"
data$X2nd_Road_Class[data$X2nd_Road_Class == 5] <- "C"
data$X2nd_Road_Class[data$X2nd_Road_Class == 6] <- "unclassified"

data$Junction_Detail[data$Junction_Detail == 0] <- "Not a junction or within 20meters"
data$Junction_Detail[data$Junction_Detail == 1] <- "Roundabout"
data$Junction_Detail[data$Junction_Detail == 2] <- "Mini-roundabout"
data$Junction_Detail[data$Junction_Detail == 3] <- "T or staggered junction"
data$Junction_Detail[data$Junction_Detail == 5] <- "Slip road"
data$Junction_Detail[data$Junction_Detail == 6] <- "Crossroads"
data$Junction_Detail[data$Junction_Detail == 7] <- "More than 4 arms(not roundabout"
data$Junction_Detail[data$Junction_Detail == 8] <- "Private drive or entrance"
data$Junction_Detail[data$Junction_Detail == 9] <- "Other junction"
data$Junction_Detail[data$Junction_Detail == -1] <- "data missing"

data$Road_Type[data$Road_Type == 1] <- "Roundabout"
data$Road_Type[data$Road_Type == 2] <- "One way street"
data$Road_Type[data$Road_Type == 3] <- "Dual carriageway"
data$Road_Type[data$Road_Type == 6] <- "single carriageway"
data$Road_Type[data$Road_Type == 7] <- "slip road"
data$Road_Type[data$Road_Type == 9] <- "unknown"
data$Road_Type[data$Road_Type == 12] <- "One way street/slip road"
data$Road_Type[data$Road_Type == -1] <- "data missing"


#2.Gis 
#Read geodatabase for Edinburgh
#Path
gdb_path <- paste0(dir_path, "/20mph.gdb")
gdb_layers <- ogrListLayers(gdb_path)

#Read shapefile
edin_cons_streets <- readOGR(dsn = gdb_path,layer="Consultation20mphStreets", verbose = FALSE)
#Put ID column as variable 
edin_cons_streets@data <-rowid_to_column(edin_cons_streets@data, "ID")
#Transform to long/lat
edin_cons_streets <- spTransform(edin_cons_streets, "+init=epsg:4326")
```

> layer =  existing 20mph
> speed limit = 30mph

```{r, echo=FALSE, warning=FALSE,message=FALSE}
#data1 <- delete_na(data[data$Junction_Detail =="Not a junction or within 20meters",],"Accident_Index")
#data1 <- delete_na(data[data$X2nd_Road_Class == "-1", ],"Accident_Index")
#data1 <- data

data1 <- new_linesdf
#data1 <- all

mergedDf <- delete_na(data1[data1$LAYER == "20mph existing streets" & data1$X1st_Road_Class == "A", ],"Accident_Index")
mergedDf <- mergedDf[,-2]
#nrow(mergedDf[mergedDf$Date >="2013-01-01" & mergedDf$Date <= "2016-12-31" , ])
#nrow(mergedDf[mergedDf$Date >="2018-01-01" & mergedDf$Date <= "2019-12-31" , ])
nrow(mergedDf)

mergedDf <- delete_na(data1[data1$LAYER == "20mph existing streets" & data1$X1st_Road_Class == "B", ],"Accident_Index")
mergedDf <- mergedDf[,-2]
nrow(mergedDf)

mergedDf <- delete_na(data1[data1$LAYER == "20mph existing streets" & data1$X1st_Road_Class == "C", ],"Accident_Index")
mergedDf <- mergedDf[,-2]
nrow(mergedDf)

mergedDf <- delete_na(data1[data1$LAYER == "20mph existing streets" & data1$X1st_Road_Class == "Unclassified", ],"Accident_Index")
mergedDf <- mergedDf[,-2]
nrow(mergedDf)
```

```{r}
#mergedDf <- data1[data1$LAYER == "Part time 20mph", ]
#mergedDf <- mergedDf[,-2]


#nrow(mergedDf[mergedDf$Date >="2013-01-01" & mergedDf$Date <= "2016-12-31" , ])
#nrow(mergedDf[mergedDf$Date >="2018-01-01" & mergedDf$Date <= "2019-12-31" , ])
#nrow(mergedDf)


mergedDf <- delete_na(data1[data1$LAYER == "Part time 20mph" & data1$X1st_Road_Class == "A", ],"Accident_Index")
mergedDf <- mergedDf[,-2]
#nrow(mergedDf[mergedDf$Date >="2013-01-01" & mergedDf$Date <= "2016-12-31" , ])
#nrow(mergedDf[mergedDf$Date >="2018-01-01" & mergedDf$Date <= "2019-12-31" , ])
nrow(mergedDf)

mergedDf <- delete_na(data1[data1$LAYER == "Part time 20mph" & data1$X1st_Road_Class == "B", ],"Accident_Index")
mergedDf <- mergedDf[,-2]
nrow(mergedDf)

mergedDf <- delete_na(data1[data1$LAYER == "Part time 20mph" & data1$X1st_Road_Class == "C", ],"Accident_Index")
mergedDf <- mergedDf[,-2]
nrow(mergedDf)

mergedDf <- delete_na(data1[data1$LAYER == "Part time 20mph" & data1$X1st_Road_Class == "Unclassified", ],"Accident_Index")
mergedDf <- mergedDf[,-2]
nrow(mergedDf)
```


> layer = 30mph 
>speed limit = 20mph

```{r, echo=FALSE, warning=FALSE,message=FALSE}
#mergedDf <- data1[data1$LAYER == "30mph" &data1$Speed_limit == 20, ]
#mergedDf <- mergedDf[,-2]

#nrow(mergedDf[mergedDf$Date >="2013-01-01" & mergedDf$Date <= "2016-12-31" , ])
#nrow(mergedDf[mergedDf$Date >="2018-01-01" & mergedDf$Date <= "2019-12-31" , ])
#nrow(mergedDf)

mergedDf <- delete_na(data1[data1$LAYER == "30mph" & data1$X1st_Road_Class == "A", ],"Accident_Index")
mergedDf <- mergedDf[,-2]
#nrow(mergedDf[mergedDf$Date >="2013-01-01" & mergedDf$Date <= "2016-12-31" , ])
#nrow(mergedDf[mergedDf$Date >="2018-01-01" & mergedDf$Date <= "2019-12-31" , ])
nrow(mergedDf)

mergedDf <- delete_na(data1[data1$LAYER == "30mph" & data1$X1st_Road_Class == "B", ],"Accident_Index")
mergedDf <- mergedDf[,-2]
nrow(mergedDf)

mergedDf <- delete_na(data1[data1$LAYER == "30mph" & data1$X1st_Road_Class == "C", ],"Accident_Index")
mergedDf <- mergedDf[,-2]
nrow(mergedDf)

mergedDf <- delete_na(data1[data1$LAYER == "30mph" & data1$X1st_Road_Class == "Unclassified", ],"Accident_Index")
mergedDf <- mergedDf[,-2]
nrow(mergedDf)
```

>layer = local 20mph
>Speed limit = 20
>NEW

```{r,echo=FALSE, warning=FALSE,message=FALSE}
#mergedDf <- data1[data1$LAYER == c("20mph local streets")  & data1$Speed_limit == 30, ]
#mergedDf <- mergedDf[mergedDf$Date >="2018-01-01" & mergedDf$Date <= "2019-12-31" , ]
#mergedDf <- mergedDf[,-2]


#nrow(mergedDf[mergedDf$Date >="2013-01-01" & mergedDf$Date <= "2016-12-31" , ])
#nrow(mergedDf[mergedDf$Date >="2018-01-01" & mergedDf$Date <= "2019-12-31" , ])
#nrow(mergedDf)


mergedDf <- delete_na(data1[data1$LAYER == "20mph local streets" & data1$X1st_Road_Class == "A", ],"Accident_Index")
mergedDf <- mergedDf[,-2]
#nrow(mergedDf[mergedDf$Date >="2013-01-01" & mergedDf$Date <= "2016-12-31" , ])
#nrow(mergedDf[mergedDf$Date >="2018-01-01" & mergedDf$Date <= "2019-12-31" , ])
nrow(mergedDf)

mergedDf <- delete_na(data1[data1$LAYER == "20mph local streets" & data1$X1st_Road_Class == "B", ],"Accident_Index")
mergedDf <- mergedDf[,-2]
nrow(mergedDf)

mergedDf <- delete_na(data1[data1$LAYER == "20mph local streets" & data1$X1st_Road_Class == "C", ],"Accident_Index")
mergedDf <- mergedDf[,-2]
nrow(mergedDf)

mergedDf <- delete_na(data1[data1$LAYER == "20mph local streets" & data1$X1st_Road_Class == "Unclassified", ],"Accident_Index")
mergedDf <- mergedDf[,-2]
nrow(mergedDf)
```
```{r}
#"20mph main streets"
#mergedDf <- data1[data1$LAYER == c( "20mph local streets")  & data1$Speed_limit == 20, ]

#mergedDf <- mergedDf[mergedDf$Date >="2018-01-01" & mergedDf$Date <= "2019-12-31" , ]
#mergedDf <- mergedDf[,-2]

#nrow(mergedDf[mergedDf$Date >="2013-01-01" & mergedDf$Date <= "2016-12-31" , ])
#mergedDf <- mergedDf[mergedDf$Date >="2013-01-01" & mergedDf$Date <= "2016-12-31" , ]
#mergedDf <- mergedDf[mergedDf$Date >="2018-01-01" & mergedDf$Date <= "2019-12-31" , ]

#nrow(mergedDf)


mergedDf <- delete_na(data1[data1$LAYER == "20mph main streets" & data1$X1st_Road_Class == "A", ],"Accident_Index")
mergedDf <- mergedDf[,-2]
#nrow(mergedDf[mergedDf$Date >="2013-01-01" & mergedDf$Date <= "2016-12-31" , ])
#nrow(mergedDf[mergedDf$Date >="2018-01-01" & mergedDf$Date <= "2019-12-31" , ])
nrow(mergedDf)

mergedDf <- delete_na(data1[data1$LAYER == "20mph main streets" & data1$X1st_Road_Class == "B", ],"Accident_Index")
mergedDf <- mergedDf[,-2]
nrow(mergedDf)

mergedDf <- delete_na(data1[data1$LAYER == "20mph main streets" & data1$X1st_Road_Class == "C", ],"Accident_Index")
mergedDf <- mergedDf[,-2]
nrow(mergedDf)

mergedDf <- delete_na(data1[data1$LAYER == "20mph main streets" & data1$X1st_Road_Class == "Unclassified", ],"Accident_Index")
mergedDf <- mergedDf[,-2]
nrow(mergedDf)
```

>layer = local 20mph
>Speed limit = 30

```{r, echo=FALSE, warning=FALSE,message=FALSE}

mergedDf <- data1[data1$LAYER == c("20mph local streets") & data1$Speed_limit == 20, ]
mergedDf <- mergedDf[mergedDf$Date >="2018-01-01" & mergedDf$Date <= "2019-12-31" , ]
#mergedDf <- mergedDf[mergedDf$Date >="2013-01-01" & mergedDf$Date <= "2016-12-31" , ]

nrow(mergedDf)

```

```{r}
mergedDf <- data1[data1$LAYER == c("20mph main streets") & data1$Speed_limit == 30, ]
mergedDf <- mergedDf[mergedDf$Date >="2013-01-01" & mergedDf$Date <= "2016-12-31" , ]

nrow(mergedDf)
```


>layer =existing  20mph
Speed limit = 20

```{r, echo=FALSE, warning=FALSE,message=FALSE}
mergedDf <- data1[data1$LAYER == c("20mph existing streets") & data1$Speed_limit == 20, ]

nrow(mergedDf[mergedDf$Date >="2013-01-01" & mergedDf$Date <= "2016-12-31" , ])
nrow(mergedDf[mergedDf$Date >="2018-01-01" & mergedDf$Date <= "2019-12-31" , ])
nrow(mergedDf)
```


```{r, echo=FALSE, warning=FALSE,message=FALSE}
mergedDf <- data1[data1$LAYER == "30mph" & data1$Speed_limit == 30, ]
nrow(mergedDf[mergedDf$Date >="2013-01-01" & mergedDf$Date <= "2016-12-31" , ])
nrow(mergedDf[mergedDf$Date >="2018-01-01" & mergedDf$Date <= "2019-12-31" , ])

nrow(mergedDf)
```


