---
title: "R Notebook"
output: html_notebook
---
```{r,echo=FALSE,warning=FALSE,message=FALSE}
# Load libraries
library(rgdal)
library(leaflet)
library(tidyverse)
library(rgeos)
library(raster)
library(ggplot2)
library(sf)
library(mapview)
library(maptools)
library(sp)
library(readxl)
library(readr)
library(knitr)
library(plyr)

source('../functions/localSnapPointsToLines.R')
source('../functions/nearest_line.R')
source('../functions/leaflet_map.R')
source('../functions/read_road_data.R')
source('../functions/filter_data.R')
source('../functions/delete_na.R')

new_nearest_line <-function(df,road_net,tolerance){
  #Create planar(cartesian) projection 
  crs <- CRS( "+proj=utm +zone=32 +ellps=WGS72 +units=m +no_defs")     # UTM zone = 32 N
  wgs84 <- CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0")  # long/lat
  
  #Convert data to planar projection  
  road_net <- spTransform(road_net,crs)
  coord <- data.frame(df$X,df$Y)
  df <-  spTransform(SpatialPointsDataFrame(coords = coord,proj4string = wgs84,data = df), crs)
  
  #Make sure our data have same projections
  proj4string(df) <- proj4string(road_net)
  
  #Find nearest line with maxDist=10m 
  nearest_line_sp <- localSnapPointsToLines(df,road_net,maxDist = tolerance,withAttrs=TRUE)
  
  return(nearest_line_sp)
}


##1.Data path 
dir_path <- "../data"
```

> Edinburgh's road network

```{r,echo=FALSE,warning=FALSE,message=FALSE} 
#Read geodatabase for Edinburgh
#Path
gdb_path <- paste0(dir_path, "/20mph.gdb")
gdb_layers <- ogrListLayers(gdb_path)

#Read shapefile
edin_cons_streets <- readOGR(dsn = gdb_path,layer="Consultation20mphStreets", verbose = FALSE)
#Put ID column as variable 
edin_cons_streets@data <-rowid_to_column(edin_cons_streets@data, "ID")
```

> Edinburgh's implementation zones

```{r,echo=FALSE,warning=FALSE,message=FALSE}
#Read shapefile
edin_impl_zones <- readOGR(dsn = gdb_path, layer= "ImplementationZones", verbose = FALSE)
#Change zone 1
edin_impl_zones@data$ImplementationZone <- as.integer(edin_impl_zones@data$ImplementationZone)
edin_impl_zones@data[6,]$ImplementationZone <- 7


#Read geodatabase for Edinburgh
#Path
gdb_path <- paste0(dir_path, "/class")
gdb_layers <- ogrListLayers(gdb_path)
#Read shapefile
edin_aclass_streets <- readOGR(dsn = gdb_path, layer = "a_road_polyline", verbose = FALSE)
proj4string(edin_aclass_streets) <- proj4string(edin_cons_streets)
edin_bclass_streets <- readOGR(dsn = gdb_path, layer = "b_road_polyline", verbose = FALSE)
proj4string(edin_bclass_streets) <- proj4string(edin_cons_streets)
edin_cclass_streets <- readOGR(dsn = gdb_path, layer = "minor_rd_polyline", verbose = FALSE)
proj4string(edin_cclass_streets) <- proj4string(edin_cons_streets)
edin_aclass_streets <- spTransform(edin_aclass_streets, "+init=epsg:4326")
edin_bclass_streets <- spTransform(edin_bclass_streets, "+init=epsg:4326")
edin_cclass_streets <- spTransform(edin_cclass_streets, "+init=epsg:4326")
```



```{r,echo=FALSE,warning=FALSE,message=FALSE}
#Transform to long/lat
edin_impl_zones <- spTransform(edin_impl_zones, "+init=epsg:4326")
edin_cons_streets <- spTransform(edin_cons_streets, "+init=epsg:4326")
edin_road_network <- edin_cons_streets
edin_road_network <- edin_road_network[edin_road_network@data$LAYER  %in% c("20mph existing streets", "20mph local streets","20mph main streets","30mph","Part time 20mph"),]
edin_road_network <- spTransform(edin_road_network,"+init=epsg:4326")
```


```{r,echo=FALSE,warning=FALSE,message=FALSE}
inter_a <- intersect(edin_aclass_streets,edin_impl_zones)
inter_b <- intersect(edin_bclass_streets,edin_impl_zones)
inter_c <- intersect(edin_cclass_streets,edin_impl_zones)
inter <- bind(inter_a,inter_b,inter_c)
inter <- spTransform(inter, "+init=epsg:4326")
inter@data <-rowid_to_column(inter@data, "ID")
edin_road_data <- read_road_data()

edin_road_data$X1st_Road_Class[edin_road_data$X1st_Road_Class == 0] <- "Not a junction or within 20meters"
edin_road_data$X1st_Road_Class[edin_road_data$X1st_Road_Class == 1] <- "Motorway"
edin_road_data$X1st_Road_Class[edin_road_data$X1st_Road_Class == 2] <- "A(M)"
edin_road_data$X1st_Road_Class[edin_road_data$X1st_Road_Class == 3] <- "A"
edin_road_data$X1st_Road_Class[edin_road_data$X1st_Road_Class == 4] <- "B"
edin_road_data$X1st_Road_Class[edin_road_data$X1st_Road_Class == 5] <- "C"
edin_road_data$X1st_Road_Class[edin_road_data$X1st_Road_Class == 6] <- "Unclassified"
```


```{r,echo=FALSE,warning=FALSE,message=FALSE}
finaldf <- nearest_line(edin_road_data,inter,15)
finaldf <- spTransform(finaldf, "+init=epsg:4326")

mergedclass <- unique(merge(data.frame(finaldf), inter, by.x = "nearest_line_id", by.y = "ID"))
mergeclass <- mergeclass[,-c(1,2,38,41,46,47,48)]
  
new_lines <- new_nearest_line(mergedclass,edin_road_network,20)
new_lines <- spTransform(new_lines, "+init=epsg:4326")
new_lines <- new_lines[,-c(2)]
new_linesdf <- unique(merge(data.frame(new_lines), edin_road_network, by.x = "nearest_line_id", by.y = "ID"))
```


```{r,echo=FALSE,warning=FALSE,message=FALSE}
Aa <- edin_aclass_streets[edin_aclass_streets@data$OSODR %in% inter_a@data$OSODR,]
Aa <- spTransform(Aa, "+init=epsg:4326")
Bb <- edin_bclass_streets[edin_bclass_streets@data$OSODR %in% inter_b@data$OSODR,]
Bb <- spTransform(Bb, "+init=epsg:4326")
minor <- edin_cclass_streets[edin_cclass_streets@data$OSODR %in% inter_c@data$OSODR,]
minor <- spTransform(minor, "+init=epsg:4326")
```

```{r,echo=FALSE,warning=FALSE,message=FALSE}
leaflet(Aa) %>% addTiles() %>% addPolylines()
leaflet(Bb) %>% addTiles() %>% addPolylines(popup = paste(Bb$ROAD_NAME,Bb$NUMBER))
```


```{r,echo=FALSE,warning=FALSE,message=FALSE}
leaflet(minor) %>% addTiles() %>% addPolylines(popup = paste(Cc$ROAD_NAME))
```


```{r,echo=FALSE,warning=FALSE,message=FALSE}
leaflet(aclass) %>% addTiles() %>% addPolylines( popup = paste(aclass$ROAD_NAME))
leaflet(bclass) %>% addTiles() %>% addPolylines(popup = paste(bclass$ROAD_NAME,bclass$NUMBER))
leaflet(minorclass) %>% addTiles() %>% addPolylines(popup = paste(minorclass$ROAD_NAME))
```


```{r,echo=FALSE,warning=FALSE,message=FALSE}
Aa <- aclass[aclass@data$OSODR %in% result$OSODR,]
Aa <- spTransform(Aa, "+init=epsg:4326")
leaflet(Aa) %>% addTiles() %>% addPolylines( popup = paste(Aa$ROAD_NAME,Aa$NUMBER))

Bb <- bclass[bclass@data$OSODR %in% result$OSODR, ]
Bb <- spTransform(Bb, "+init=epsg:4326")
leaflet(Bb) %>% addTiles() %>% addPolylines( popup = paste(Bb$ROAD_NAME,Bb$NUMBER))

minor <- minorclass[minorclass@data$OSODR %in% result$OSODR,]
minor <- spTransform(minor, "+init=epsg:4326")
leaflet(minor) %>% addTiles() %>% addPolylines( popup = paste(minor$ROAD_NAME,minor$NUMBER))
```


```{r,echo=FALSE,warning=FALSE,message=FALSE}
aclass_sf <- st_as_sf(Aa)
leaflet() %>%
  addTiles() %>%
  addPolylines(data = aclass_sf, color = c("red"))
bclass_sf <- st_as_sf(Bb)
minorclass_sf <- st_as_sf(minor)
edin_road_network_sf <- st_as_sf(edin_road_network)
edin_class <- rbind(aclass_sf,bclass_sf,minorclass_sf)


result <-  st_intersection(edin_road_network_sf,edin_class)
leaflet() %>% addTiles() %>% addPolylines(data = result)
result$geometry_type <- st_geometry_type(result)
#result <- result[result$geometry_type == "MULTIPOINT",]
result_a <- st_intersection(edin_road_network_sf,aclass_sf)
result_a$geometry_type <- st_geometry_type(result_a)
#result_a <- result_a[result_a$geometry_type == "MULTIPOINT",]
result_b <- st_intersection(edin_road_network_sf,bclass_sf)
result_b$geometry_type <- st_geometry_type(result_b)
#result_b <- result_b[result_b$geometry_type == "MULTIPOINT",]
result_minor <- st_intersection(edin_road_network_sf,minorclass_sf)
result_minor$geometry_type <- st_geometry_type(result_minor)
#result_minor <- result_minor[result_minor$geometry_type == "MULTIPOINT",]


final_result <- rbind(result_a,result_b,result_minor)


df <- data.frame(nearest_road)

#Create planar(cartesian) projection 
crs <- CRS( "+proj=utm +zone=32 +ellps=WGS72 +units=m +no_defs")     # UTM zone = 32 N
wgs84 <- CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0")  # long/lat
  
#Convert data to planar projection  
coord <- data.frame(df$Y, df$X)
df <-  spTransform(SpatialPointsDataFrame(coords = coord, proj4string = wgs84, data = df), crs)
  
leaflet(minor) %>% addTiles() %>% addPolylines() %>%addMarkers(lng = df$X, lat = df$Y)
  

nearest_line <-function(df,road_net,tolerance){
  #Create planar(cartesian) projection 
  crs <- CRS( "+proj=utm +zone=32 +ellps=WGS72 +units=m +no_defs")     # UTM zone = 32 N
  wgs84 <- CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0")  # long/lat
  
  #Convert data to planar projection  
  road_net <- spTransform(road_net,crs)
  coord <- data.frame(df$Longitude,df$Latitude)
  df <-  spTransform(SpatialPointsDataFrame(coords = coord,proj4string = wgs84,data = df), crs)
  
  #Make sure our data have same projections
  proj4string(df) <- proj4string(road_net)
  
  #Find nearest line with maxDist=6m 
  nearest_line_sp <- localSnapPointsToLines(df,road_net,maxDist = tolerance,withAttrs=TRUE)
  
  return(nearest_line_sp)
}

finaldf <- nearest_line(df,inter_a,10)

```


```{r,echo=FALSE,warning=FALSE,message=FALSE}
edin_road_data <- read_road_data()
```


```{r,echo=FALSE,warning=FALSE,message=FALSE}
nearest_road <- nearest_line(edin_road_data, edin_road_network, 10)
nearest_road <- spTransform(nearest_road, "+init=epsg:4326")
```


```{r,echo=FALSE,warning=FALSE,message=FALSE}
select <- nearest_road@data[nearest_road$year != 2019 , ]
mergea <- merge(select, result, by.x = "nearest_line_id", by.y = "ID")
mergea <- mergea[,-c(46:51)]
mergea <- unique(mergea)

not <- delete_na(data.frame(nearest_road)[!(nearest_road@data$Accident_Index %in% mergea$Accident_Index),],"Accident_Index")
not_2019 <- not[not$year == 2019, ]
not <- unique(not[not$year != 2019, ])

mergenot <- merge(not, edin_road_network@data, by.x = "nearest_line_id", by.y = "ID")
if(mergenot$FEATID == result$FEATID & mergenot$LAYER == result$LAYER ){
mergenot$CODE <- result$CODE
}

```


```{r,echo=FALSE,warning=FALSE,message=FALSE}
mergedDf <- unique(merge(data.frame(nearest_road), result, by.x = "nearest_line_id", by.y = "ID"))
#mergedDf <- mergedDf[, -c(41,46,47,50,51)]

mergedDf$X1st_Road_Class[mergedDf$X1st_Road_Class == 0] <- "Not a junction or within 20meters"
mergedDf$X1st_Road_Class[mergedDf$X1st_Road_Class == 1] <- "Motorway"
mergedDf$X1st_Road_Class[mergedDf$X1st_Road_Class == 2] <- "A(M)"
mergedDf$X1st_Road_Class[mergedDf$X1st_Road_Class == 3] <- "A"
mergedDf$X1st_Road_Class[mergedDf$X1st_Road_Class == 4] <- "B"
mergedDf$X1st_Road_Class[mergedDf$X1st_Road_Class == 5] <- "C"
mergedDf$X1st_Road_Class[mergedDf$X1st_Road_Class == 6] <- "Unclassified"

backup <- mergedDf

merged <- delete_na(mergedDf[mergedDf$X2nd_Road_Class != "-1" & mergedDf$geometry_type == "MULTIPOINT", ],"Accident_Index")
merged <- merged[,-c(4,5:16,18:34,38:41,44)]
```


```{r,echo=FALSE,warning=FALSE,message=FALSE}
copy_a <- as.data.frame(merged[merged$X1st_Road_Class == "A" & merged$CODE == 3001, ])
copy_a <- unique(delete_na(copy_a,"Accident_Index"))

copy_b <- as.data.frame(merged[merged$X1st_Road_Class == "B" & merged$CODE == 3002, ])
copy_b <- unique(delete_na(copy_b,"Accident_Index"))

copy_c <- as.data.frame(merged[merged$X1st_Road_Class == "C" & merged$CODE == 3004, ])
copy_c <- unique(delete_na(copy_c,"Accident_Index"))

copy_un <- as.data.frame(merged[merged$X1st_Road_Class == "Unclassified" & merged$CODE == 3004, ])
copy_un <- unique(delete_na(copy_un,"Accident_Index"))

final <- unique(rbind(copy_a,copy_b,copy_c,copy_un))
final <- final[,-c(6,7,11:16)]
final <- unique(final)
```


```{r,echo=FALSE,warning=FALSE,message=FALSE}
not_found <- delete_na(merged[!(merged$Accident_Index %in% final$Accident_Index),],"Accident_Index")
not_found_2019 <- mergedDf[mergedDf$year == "2019", ]
```



```{r,echo=FALSE,warning=FALSE,message=FALSE}
leaflet_map(mergedDf[mergedDf$Date >= "2013-07-31" & mergedDf$Date <= "2014-07-30" ,],edin_cons_streets)
```


```{r,echo=FALSE,warning=FALSE,message=FALSE}
copy_a <- as.data.frame(result[result$X1st_Road_Class == "A" & result$CODE == 3001, ])
copy_a <- unique(merge(data.frame(nearest_road), copy_a, by.x = "nearest_line_id", by.y = "ID"))


copy_b <- as.data.frame(merged[merged$X1st_Road_Class == "B" & merged$CODE == 3002, ])

copy_b <- unique(delete_na(copy_b,"Accident_Index"))

copy_c <- as.data.frame(merged[merged$X1st_Road_Class == "C" & merged$CODE == 3004, ])
copy_c <- copy_c[,-c(42)]
copy_c <- unique(delete_na(copy_c,"Accident_Index"))

copy_un <- as.data.frame(merged[merged$X1st_Road_Class == "Unclassified" & merged$CODE == 3004, ])
copy_un <- copy_un[,-c(42)]
copy_un <- unique(delete_na(copy_un,"Accident_Index"))

final <- unique(rbind(copy_a,copy_b,copy_c,copy_un))
final <- final[,-c(1,7,11,14)]
```

