---
title: "R Notebook"
output: html_notebook
---
```{r}
# Load libraries
library(rgdal)
library(leaflet)
library(tidyverse)
library(rgeos)
library(raster)
library(ggplot2)
library(sf)
library(mapview)
library(maptools)
library(sp)
library(readxl)
library(readr)
library(knitr)
library(plyr)

source('../functions/localSnapPointsToLines.R')
source('../functions/nearest_line.R')
source('../functions/leaflet_map.R')
source('../functions/read_road_data.R')
source('../functions/filter_data.R')
source('../functions/delete_na.R')


##1.Data path 
dir_path <- "../data"
```

> Edinburgh's road network

```{r,echo=FALSE,warning=FALSE,message=FALSE} 
#Read geodatabase for Edinburgh
#Path
gdb_path <- paste0(dir_path, "/20mph.gdb")
gdb_layers <- ogrListLayers(gdb_path)

#Read shapefile
edin_cons_streets <- readOGR(dsn = gdb_path,layer="Consultation20mphStreets", verbose = FALSE)
#Put ID column as variable 
edin_cons_streets@data <-rowid_to_column(edin_cons_streets@data, "ID")
```

> Edinburgh's implementation zones

```{r,echo=FALSE,warning=FALSE,message=FALSE}
#Read shapefile
edin_impl_zones <- readOGR(dsn = gdb_path, layer= "ImplementationZones", verbose = FALSE)
#Change zone 1
edin_impl_zones@data$ImplementationZone <- as.integer(edin_impl_zones@data$ImplementationZone)
edin_impl_zones@data[6,]$ImplementationZone <- 7
```



```{r,echo=FALSE,warning=FALSE,message=FALSE}
#Read geodatabase for Edinburgh
#Path
gdb_path <- paste0(dir_path, "/class")
gdb_layers <- ogrListLayers(gdb_path)

#Read shapefile
edin_aclass_streets <- readOGR(dsn = gdb_path, layer = "a_road_polyline", verbose = FALSE)
proj4string(edin_aclass_streets) <- proj4string(edin_cons_streets)
edin_bclass_streets <- readOGR(dsn = gdb_path, layer = "b_road_polyline", verbose = FALSE)
proj4string(edin_bclass_streets) <- proj4string(edin_cons_streets)
edin_aclass_streets <- spTransform(edin_aclass_streets, "+init=epsg:4326")
edin_bclass_streets <- spTransform(edin_bclass_streets, "+init=epsg:4326")
```



```{r}
#Transform to long/lat
edin_impl_zones <- spTransform(edin_impl_zones, "+init=epsg:4326")
edin_cons_streets <- spTransform(edin_cons_streets, "+init=epsg:4326")
edin_road_network <- edin_cons_streets
edin_road_network <- edin_road_network[edin_road_network@data$LAYER  %in% c("20mph existing streets", "20mph local streets","20mph main streets","30mph","Part time 20mph"),]
edin_road_network <- spTransform(edin_road_network,"+init=epsg:4326")
```


```{r}
#R 64 bit
#proj4string(edin_aclass_streets) <- proj4string(edin_road_network)
#result <- intersect(edin_aclass_streets,edin_road_network)
inter_a <- intersect(edin_aclass_streets,edin_impl_zones)
inter_b <- intersect(edin_bclass_streets,edin_impl_zones)

Aa <- edin_aclass_streets[edin_aclass_streets@data$OSODR %in% inter_a@data$OSODR,]
Aa <- spTransform(Aa, "+init=epsg:4326")

Bb <- edin_bclass_streets[edin_bclass_streets@data$OSODR %in% inter_b@data$OSODR,]
Bb <- spTransform(Bb, "+init=epsg:4326")

leaflet(Aa) %>% addTiles() %>% addPolylines()
leaflet(Bb) %>% addTiles() %>% addPolylines()
```




```{r,echo=FALSE,warning=FALSE,message=FALSE}
aclass_copy <- st_as_sf(Aa)
bclass_copy <- st_as_sf(Bb)
edin_road_network_copy <- st_as_sf(edin_road_network)
edin_class <- rbind(aclass_copy,bclass_copy)
  
result <- st_intersection(edin_class,edin_road_network_copy)
result$NUMBER <- as.character(result$NUMBER)
result$class <- substring(result$NUMBER,1,1)
```


```{r,echo=FALSE,warning=FALSE,message=FALSE}
edin_road_data <- read_road_data()
casualties_data <- read_csv(paste0(dir_path, "/edin_casualties_data.csv"))
```


```{r,echo=FALSE,warning=FALSE,message=FALSE}
nearest_road <- nearest_line(edin_road_data,edin_road_network,10)
nearest_road <- spTransform(nearest_road,"+init=epsg:4326")
```


```{r,echo=FALSE,warning=FALSE,message=FALSE}
mergedDf <- unique(merge(data.frame(nearest_road),result,by.x = "nearest_line_id" ,by.y = "ID"))
mergedDf <- mergedDf[, -c(41,46,47,50,51)]
#check duplicates
```


```{r,echo=FALSE,warning=FALSE,message=FALSE}
mergedDf$X1st_Road_Class[mergedDf$X1st_Road_Class == 0] <- "Not a junction or within 20meters"
mergedDf$X1st_Road_Class[mergedDf$X1st_Road_Class == 1] <- "Motorway"
mergedDf$X1st_Road_Class[mergedDf$X1st_Road_Class == 2] <- "A(M)"
mergedDf$X1st_Road_Class[mergedDf$X1st_Road_Class == 3] <- "A"
mergedDf$X1st_Road_Class[mergedDf$X1st_Road_Class == 4] <- "B"
mergedDf$X1st_Road_Class[mergedDf$X1st_Road_Class == 5] <- "C"
mergedDf$X1st_Road_Class[mergedDf$X1st_Road_Class == 6] <- "Unclassified"
```

```{r}
leaflet_map(mergedDf[mergedDf$Date >= "2013-07-31" & mergedDf$Date <= "2014-07-30" ,],edin_cons_streets)
```

